NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-301-CA7.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-301-CA7.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-301-CA7.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-301-CA7.pem
    OrganizationalUnitIdentifier: orderer
